-- Insert default roles
INSERT INTO roles (name, created_at) VALUES
('ROLE_USER', CURRENT_TIMESTAMP),
('ROLE_ADMIN', CURRENT_TIMESTAMP),
('ROLE_RESEARCHER', CURRENT_TIMESTAMP),
('ROLE_FIELD_WORKER', CURRENT_TIMESTAMP);
